language: ruby

before_install:
  - gem update --system
  - gem --version

install:
  - gem install github-pages
  - gem install public_suffix
  - gem install html-proofer

before_script: bundle exec jekyll build

script: htmlproof _site