language: ruby
before_install:
  - gem update --system
  - gem --version
script: "bundle exec jekyll build"
rvm:
  - "2.1.0"
  - "1.9.3"
  - "1.9.2"
  - jruby-19mode
  - rbx
  - jruby-18mode
  - "1.8.7"